export const dark = {
  // '--bg-color': '#000',
  '--about-bg-color': '#181818',
  '--sub-bg-color': '#131313',
  '--nav-bg-color': 'rgba(0,0,0,0.8)',
  '--primary-color': '#E8E8E8',
  '--minor-color': '#A3A3A3',
  '--label-color': '#807C7C',
  '--header-sub-title-color': '#a4a1a2',
  '--nav-name-color': '#E8E8E8',
  '--dot-color': 'transparent',
  '--dot-active-color': '#fff',
  '--title-gradient-up': '#413113',
  '--title-gradient-down': '#131313',
  '--introduce-bg-color': '#181818',
  '--introduce-color': '#A3A3A3',
  '--footer-border-color': '#161616',
  '--theme-switch-bg-color': '#242123',
  '--theme-switch-line-color': '#3c3a3a',
};
export const light = {
  '--bg-color': '#FAFAFA',
  '--about-bg-color': '#FAFAFA',
  '--sub-bg-color': '#fff',
  '--nav-bg-color': 'rgba(250,250,250,0.8)',
  '--primary-color': '#404040',
  '--minor-color': '#807C7C',
  '--label-color': '#A3A3A3',
  '--header-sub-title-color': '#807c7c',
  '--nav-name-color': '#807c7c',
  '--dot-color': 'transparent',
  '--dot-active-color': '#404040',
  '--title-gradient-up': '#FFF7CD',
  '--title-gradient-down': '#fff',
  '--introduce-bg-color': '#FAFAFA',
  '--introduce-color': '#7c7070',
  '--footer-border-color': '#EFEFEF',
  '--theme-switch-bg-color': '#fff',
  '--theme-switch-line-color': '#D7D3CD',
}